name: Terraform CI

on:
    push:

    pull_request:
        branches:
        - main
        - develop

defaults:
  run:
    working-directory: terraform

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.6.0
        - name: Terraform format
          run: terraform fmt -check
        - name: Terraform init
          run: terraform init
        - name: terraform validate
          run: terraform validate